name: hoteljobber_employer
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 40.0.0+10208

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.3
  # get: ^4.6.6
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  auto_route: ^9.2.2
  internet_connection_checker_plus: ^2.5.2
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  sms_autofill: ^2.4.1
  flutter_typeahead: ^5.2.0
  fluttertoast: ^8.2.8
  carousel_slider: ^5.0.0
  transparent_image: ^2.0.1
  location: ^7.0.1
  url_launcher: ^6.3.1
  crop_your_image: ^1.1.0
  path_provider: ^2.1.5
  smooth_page_indicator: ^1.2.0+3
  flutter_spinkit: ^5.2.1
  flutter_image_compress: ^2.3.0
  timeago: ^3.7.0
  flutter_rating_bar: ^4.0.1
  in_app_update: ^4.2.3
  animated_bottom_navigation_bar: ^1.3.3
  lottie: ^3.1.3
  dismissible_page: ^1.0.2
  # razorpay_flutter: ^1.3.7
  geocoding: ^3.0.0
  google_maps_flutter: ^2.9.0
  device_info_plus: ^11.1.1
  package_info_plus: ^8.1.1
  android_id: ^0.4.0
  flutter_screenutil: ^5.9.3
  dio: ^5.7.0
  # pretty_dio_logger: ^1.4.0
  talker_dio_logger: ^4.5.4
  retrofit: ^4.4.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  get_it: ^8.0.2
  injectable: ^2.5.0
  flutter_dotenv: ^5.2.1
  safe_device: ^1.1.9
  no_screenshot: ^0.3.1
  easy_localization: ^3.0.7
  loader_overlay: ^4.0.3

  firebase_core: ^3.7.0
  firebase_storage: ^12.3.5
  firebase_messaging: ^15.1.4
  firebase_auth: ^5.3.2
  firebase_remote_config: ^5.1.4
  google_sign_in: ^6.2.2
  firebase_crashlytics: ^4.1.4

  # Local Storage Libraries
  flutter_secure_storage: ^9.2.2
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.1
  auto_route_generator: ^9.0.0
  retrofit_generator: ^9.1.4
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2

flutter_icons:
  image_path: "assets/images/launcher_icon/launcher_icon.jpeg"
  ios: true
  android: true

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/constants/image
  filename: image_constants.dart
  classname: ImageConstants

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/lottie/
    - assets/images/gifs/
    - assets/images/background/
    - assets/images/logos/
    - assets/images/splash/
    - assets/images/icons/
    - assets/images/launcher_icon/
    - assets/images/dashboard_icons/
    - assets/images/job_details_icons/
    - assets/images/default_profile_images/
    - assets/lottie/
    - .env

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
